# Generated by Django 4.0.4 on 2022-07-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.AddField(
            model_name="product",
            name="bid",
            field=models.ManyToManyField(
                blank=True, related_name="bids_in_the_auction", to="auctions.bids"
            ),
        ),
    ]
