# Generated by Django 4.0.4 on 2022-07-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_remove_product_is_active_product_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="bid",
            new_name="bids",
        ),
    ]
