# Generated by Django 4.0.4 on 2022-07-23 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_bid_product_bids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="comments",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="bidded",
            field=models.ForeignKey(
                blank=True,
                default=0,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_bid_for_the_auction",
                to="auctions.bids",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
