# Generated by Django 4.0.4 on 2022-07-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_comments_body_alter_comments_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="bid",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="bidded",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_bid_for_the_auction",
                to="auctions.bids",
            ),
        ),
    ]
